[workspace]
name = "rayforge"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi]
workdir = ".."

[environments]
default = { features = ["build"] }

[feature.build.dependencies]
adwaita-icon-theme = "*"
cairo = "*"
gettext = "*"
glib = "*"
gobject-introspection = "*"
gtk4 = "*"
libadwaita = "*"
libheif = "*"
librsvg = ">=2.58.4,<3"
nsis = "*"
openslide = "*"
pkg-config = "*"
pkgconf = "*"
poppler = "*"
pycairo = "==1.28.0"
PyGObject = "==3.50.0"
pyinstaller = "*"
python = ">=3.11"
rust = "*"

[feature.build.pypi-dependencies]
rayforge = { editable = true, path = ".." }
pytest = "*"
pytest-asyncio = "*"
pytest-mock = "*"
pytest-cov = "*"

[tasks]
compile-translations = "bash scripts/update_translations.sh --compile-only"

[tasks.test]
env = { GI_TYPELIB_PATH = "$(pkgconf --variable=typelibdir gobject-introspection-1.0)" }
cmd = "pwd && ls tests/ && pytest -v --ignore=tests/ui_gtk --tb=short -rA"

[tasks.build]
env = { GI_TYPELIB_PATH = "$(pkgconf --variable=typelibdir gobject-introspection-1.0)" }
cmd = "bash scripts/win/pixi_win_build.sh"
depends-on = ["compile-translations"]
