name: Pixi Test
on:
  push:
    branches:
      - '**'  # Run on all branches
    tags:
      - '*'  # Include tags to trigger builds
  pull_request:
    branches:
      - '**'  # Run on PRs targeting any branch
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  pixi-test:
    name: Pixi Lint and Test Rayforge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.31.0
          cache: true
          cache-key: ${{ github.sha }}

      - name: Setup Pixi environment
        run: pixi install

      - name: Compile Translations
        run: pixi run compile-translations

      - name: Run flake8 Lint
        run: pixi run lint

      - name: Run tests
        run: pixi run test
