name: Build and Publish Wheel
on:
  push:
    tags:
      - '*'

jobs:
  lint-test:
    if: github.repository == 'barebaric/rayforge'
    uses: ./.github/workflows/lint-test.yml

  build-publish-wheel:
    name: Build and Publish Wheel
    needs: [lint-test]  # Run only if tests pass
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Compile Translations
        uses: ./.github/actions/compile-translations

      - name: Build a wheel
        run: |
          git status
          git describe
          python3 -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
