name: Build and Publish Snap
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  lint-test:
    if: github.repository == 'barebaric/rayforge'
    uses: ./.github/workflows/lint-test.yml

  build-publish-snap:
    name: Build and Publish Snap
    needs: [lint-test]  # Run only if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest

      - name: Compile Translations
        run: pixi run compile-translations

      - name: Build snap
        uses: snapcore/action-build@v1
        id: build

      - name: Test built snap
        run: |
          sudo snap install ${{ steps.build.outputs.snap }} --dangerous
          rayforge --help

      - name: Publish to Snapcraft
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          # Push to stable and edge on tagged releases, otherwise just edge.
          release: ${{ startsWith(github.ref, 'refs/tags/') && 'stable,edge' || 'edge' }}
