name: Build and Publish Wheel
on:
  push:
    tags:
      - '*'

jobs:
  lint-test:
    if: github.repository == 'barebaric/rayforge'
    uses: ./.github/workflows/lint-test.yml

  build-publish-wheel:
    name: Build and Publish Wheel
    needs: [lint-test]  # Run only if tests pass
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest

      - name: Build wheel with Pixi
        run: |
          pixi run wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
